# Generated by Django 2.0.5 on 2018-05-04 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('test_datetime', models.DateTimeField(verbose_name='test_time')),
                ('test_level', models.CharField(choices=[('MK', 'MK'), ('MP1', 'MP1'), ('MP2', 'MP2'), ('MP3', 'MP3'), ('MP4', 'MP4')], default='MK', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(verbose_name='birthday')),
                ('gender', models.CharField(choices=[('BY', 'Boy'), ('GR', 'Girl')], default='BY', max_length=2)),
                ('current_school_name', models.CharField(max_length=50)),
                ('current_school_grade', models.CharField(choices=[('K1', '幼末'), ('K2', '幼小'), ('K3', '幼中'), ('K4', '幼大'), ('P1', '小一'), ('P2', '小二')], default='K1', max_length=2)),
                ('name_en', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
